export interface AttractionConfig {
  name: string; // partial match key against queue-times.com ride names
  isShow: boolean;
  displayName?: string; // override the API name for display
}

export const ATTRACTIONS: Record<number, AttractionConfig[]> = {
  6: [ // Magic Kingdom
    { name: 'AstroOrbiter', isShow: false },
    { name: 'Barnstormer', isShow: false },
    { name: 'Big Thunder Mountain', isShow: false },
    { name: 'Buzz Lightyear', isShow: false },
    { name: 'Country Bear', isShow: false },
    { name: 'Dapper Dan', isShow: true },
    { name: 'Dumbo', isShow: false },
    { name: 'Enchanted Tales with Belle', isShow: false },
    { name: 'Hall of Presidents', isShow: false },
    { name: 'Haunted Mansion', isShow: false },
    { name: 'Small World', isShow: false },
    { name: "Jessie", isShow: true },
    { name: 'Jungle Cruise', isShow: false },
    { name: 'Mad Tea Party', isShow: false },
    { name: 'Magic Carpets of Aladdin', isShow: false },
    { name: 'Winnie the Pooh', isShow: false },
    { name: 'Meet Ariel', isShow: false },
    { name: 'Meet Cinderella', isShow: false, displayName: 'Meet Cinderella and Tiana' },
    { name: 'Visiting Princesses', isShow: false, displayName: 'Meet Visiting Princesses' },
    { name: 'Town Square Theater', isShow: false },
    { name: 'PhilharMagic', isShow: false },
    { name: 'Laugh Floor', isShow: false },
    { name: "Peter Pan", isShow: false },
    { name: 'Pirates of the Caribbean', isShow: false },
    { name: 'Regal Carrousel', isShow: false },
    { name: 'Seven Dwarfs Mine Train', isShow: false },
    { name: 'Space Mountain', isShow: false },
    { name: 'Swiss Family Treehouse', isShow: false },
    { name: 'Bayou Adventure', isShow: false },
    { name: 'Tomorrowland Speedway', isShow: false },
    { name: 'PeopleMover', isShow: false, displayName: 'Tomorrowland PeopleMover' },
    { name: 'TRON', isShow: false },
    { name: 'Journey of the Little Mermaid', isShow: false, displayName: 'Under the Sea' },
    { name: 'Carousel of Progress', isShow: false },
    { name: 'Enchanted Tiki Room', isShow: false },
  ],
  5: [ // EPCOT
    { name: 'American Adventure', isShow: true },
    { name: 'Awesome Planet', isShow: false },
    { name: 'Beauty and the Beast Sing-Along', isShow: true },
    { name: 'Canada Far and Wide', isShow: false, displayName: 'Canada Far and Wide' },
    { name: 'Short Film Festival', isShow: false },
    { name: 'Frozen', isShow: false },
    { name: 'Goofy', isShow: false },
    { name: 'Grand Fiesta Tour', isShow: false },
    { name: 'Guardians of the Galaxy', isShow: false, displayName: 'Guardians of the Galaxy' },
    { name: 'Journey Into Imagination', isShow: false },
    { name: 'Journey of Water', isShow: false },
    { name: 'Living with the Land', isShow: false },
    { name: 'Mickey & Friends', isShow: false, displayName: 'Meet Mickey & Friends' },
    { name: 'Mission: SPACE', isShow: false },
    { name: 'Reflections of China', isShow: true },
    { name: 'Ratatouille', isShow: false },
    { name: 'Seas with Nemo', isShow: false },
    { name: 'Soarin', isShow: false },
    { name: 'Spaceship Earth', isShow: false },
    { name: 'Test Track', isShow: false },
    { name: 'Turtle Talk', isShow: false },
    { name: 'Voices of Liberty', isShow: true },
    { name: 'Encanto', isShow: true },
  ],
  7: [ // Hollywood Studios
    { name: 'Alien Swirling Saucers', isShow: false },
    { name: 'Beauty and the Beast', isShow: true, displayName: 'Beauty and the Beast – Live' },
    { name: 'Disney Junior', isShow: true },
    { name: 'Disney Villains', isShow: true },
    { name: 'Frozen Sing-Along', isShow: true, displayName: 'For the First Time in Forever' },
    { name: 'Indiana Jones', isShow: true, displayName: 'Indiana Jones' },
    { name: 'Little Mermaid', isShow: true, displayName: 'The Little Mermaid - Musical' },
    { name: 'Meet Ariel', isShow: false },
    { name: 'Red Carpet Dreams', isShow: false },
    { name: 'Edna Mode', isShow: false, displayName: 'Meet Edna Mode' },
    { name: 'Olaf', isShow: false },
    { name: 'Runaway Railway', isShow: false },
    { name: "Millennium Falcon", isShow: false },
    { name: 'Roller Coaster', isShow: false, displayName: "Rock 'n' Roller Coaster" },
    { name: 'Slinky Dog Dash', isShow: false },
    { name: 'Star Tours', isShow: false },
    { name: 'Rise of the Resistance', isShow: false },
    { name: 'Toy Story Mania', isShow: false },
    { name: 'Tower of Terror', isShow: false },
  ],
  8: [ // Animal Kingdom
    { name: 'Flight of Passage', isShow: false },
    { name: 'Bluey', isShow: true, displayName: "Bluey's Wild World" },
    { name: 'Expedition Everest', isShow: false, displayName: 'Expedition Everest' },
    { name: 'Feather Friends', isShow: true },
    { name: 'Festival of the Lion King', isShow: true },
    { name: 'Finding Nemo', isShow: true, displayName: 'Finding Nemo: The Big Blue' },
    { name: 'Gorilla Falls', isShow: false },
    { name: 'Kali River Rapids', isShow: false },
    { name: 'Kilimanjaro Safaris', isShow: false },
    { name: 'Maharajah Jungle Trek', isShow: false },
    { name: 'Adventures Outpost', isShow: false },
    { name: 'River Journey', isShow: false },
    { name: 'Wildlife Express', isShow: false },
    { name: 'Zootopia', isShow: false },
  ],
};
