export interface AttractionConfig {
  name: string; // partial match key against queue-times.com ride names
  isShow: boolean;
}

export const ATTRACTIONS: Record<number, AttractionConfig[]> = {
  6: [ // Magic Kingdom
    { name: 'AstroOrbiter', isShow: false },
    { name: 'Barnstormer', isShow: false },
    { name: 'Big Thunder Mountain', isShow: false },
    { name: 'Buzz Lightyear', isShow: false },
    { name: 'Country Bear', isShow: true },
    { name: 'Dapper Dan', isShow: true },
    { name: 'Dumbo', isShow: false },
    { name: 'Enchanted Tales with Belle', isShow: true },
    { name: 'Hall of Presidents', isShow: true },
    { name: 'Haunted Mansion', isShow: false },
    { name: "It's a Small World", isShow: false },
    { name: "Jessie", isShow: true },
    { name: 'Jungle Cruise', isShow: false },
    { name: 'Mad Tea Party', isShow: false },
    { name: 'Magic Carpets of Aladdin', isShow: false },
    { name: 'Winnie the Pooh', isShow: false },
    { name: 'Meet Ariel', isShow: false },
    { name: 'Princess Fairytale Hall', isShow: false },
    { name: 'Town Square Theater', isShow: false },
    { name: 'PhilharMagic', isShow: true },
    { name: 'Laugh Floor', isShow: true },
    { name: "Peter Pan", isShow: false },
    { name: 'Pirates of the Caribbean', isShow: false },
    { name: 'Regal Carrousel', isShow: false },
    { name: 'Seven Dwarfs Mine Train', isShow: false },
    { name: 'Space Mountain', isShow: false },
    { name: 'Swiss Family Treehouse', isShow: false },
    { name: "Tiana's Bayou Adventure", isShow: false },
    { name: 'Tomorrowland Speedway', isShow: false },
    { name: 'PeopleMover', isShow: false },
    { name: 'TRON', isShow: false },
    { name: 'Journey of the Little Mermaid', isShow: false },
    { name: 'Carousel of Progress', isShow: true },
    { name: 'Enchanted Tiki Room', isShow: true },
  ],
  5: [ // EPCOT
    { name: 'American Adventure', isShow: true },
    { name: 'Awesome Planet', isShow: true },
    { name: 'Beauty and the Beast Sing-Along', isShow: true },
    { name: 'Canada Far and Wide', isShow: true },
    { name: 'Short Film Festival', isShow: true },
    { name: 'Frozen Ever After', isShow: false },
    { name: 'Goofy', isShow: false },
    { name: 'Grand Fiesta Tour', isShow: false },
    { name: 'Guardians of the Galaxy', isShow: false },
    { name: 'Journey Into Imagination', isShow: false },
    { name: 'Journey of Water', isShow: false },
    { name: 'Living with the Land', isShow: false },
    { name: 'Mickey & Friends', isShow: false },
    { name: 'Mission: SPACE', isShow: false },
    { name: 'Reflections of China', isShow: true },
    { name: "Remy's Ratatouille", isShow: false },
    { name: 'Seas with Nemo', isShow: false },
    { name: "Soarin'", isShow: false },
    { name: 'Spaceship Earth', isShow: false },
    { name: 'Test Track', isShow: false },
    { name: 'Turtle Talk', isShow: true },
    { name: 'Voices of Liberty', isShow: true },
    { name: 'Encanto', isShow: true },
  ],
  7: [ // Hollywood Studios
    { name: 'Alien Swirling Saucers', isShow: false },
    { name: 'Beauty and the Beast', isShow: true },
    { name: 'Disney Junior', isShow: true },
    { name: 'Disney Villains', isShow: true },
    { name: 'Frozen Sing-Along', isShow: true },
    { name: 'Indiana Jones', isShow: true },
    { name: 'Little Mermaid', isShow: true },
    { name: 'Meet Ariel', isShow: false },
    { name: 'Red Carpet Dreams', isShow: false },
    { name: 'Edna Mode', isShow: false },
    { name: 'Olaf', isShow: false },
    { name: "Mickey & Minnie's Runaway Railway", isShow: false },
    { name: "Millennium Falcon", isShow: false },
    { name: "Rock 'n' Roller Coaster", isShow: false },
    { name: 'Slinky Dog Dash', isShow: false },
    { name: 'Star Tours', isShow: false },
    { name: 'Rise of the Resistance', isShow: false },
    { name: 'Toy Story Mania', isShow: false },
    { name: 'Tower of Terror', isShow: false },
  ],
  8: [ // Animal Kingdom
    { name: 'Flight of Passage', isShow: false },
    { name: "Bluey", isShow: true },
    { name: 'Expedition Everest', isShow: false },
    { name: 'Feather Friends', isShow: true },
    { name: 'Festival of the Lion King', isShow: true },
    { name: 'Finding Nemo', isShow: true },
    { name: 'Gorilla Falls', isShow: false },
    { name: 'Kali River Rapids', isShow: false },
    { name: 'Kilimanjaro Safaris', isShow: false },
    { name: 'Maharajah Jungle Trek', isShow: false },
    { name: 'Adventures Outpost', isShow: false },
    { name: "Na'vi River Journey", isShow: false },
    { name: 'Wildlife Express', isShow: false },
    { name: 'Zootopia', isShow: false },
  ],
};
